host: 127.0.0.1
port: 4004
url: "https://blog.keboola.com"
permalink: :title
future: true
highlighter: true
exclude: ['Rakefile.rb', 'CNAME', 'README.md', 'config.codekit3', 'Gemfile*', 'less', 'js/global.js']
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 10
  permalink: '/:num/'
  title: ' - Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true