---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: documents
  templates:
  - post
- type: directory
  path: categories
  label: Categories
  create: documents
  match: "**/*"
- type: directory
  path: _data
  label: Users
  create: none
  match: "**/*.{json,yaml,yml}"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
